version: '3.8'
services:
  web:
    build:
      context: ../../
      dockerfile: container/development/Dockerfile.frontend
    ports:
      - 8080:8080
    volumes:
      - ../../:/srv/ombruk-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
