FROM gradle:6.5.0-jdk8

COPY ./backend /srv/ombruk-backend
COPY ./container/development/wait-for-it.sh /opt

WORKDIR /srv/ombruk-backend

EXPOSE 8080

CMD gradle run & ../../opt/wait-for-it.sh 0.0.0.0:8080 -t 0 -- gradle -t installDist --watch-fs
